using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Data.SQLite;
using PMQuanLy.Model;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraGrid.Views.Grid.ViewInfo;
using System.Collections;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraEditors.Repository;

namespace PMQuanLy
{
    public partial class MainForm : Form
    {
        ListProductModel mProduct;
        InventoryModel mInventory;
        private DataTable dtProduct, dtInventory, dtOrder;

        public MainForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDSInventory.Fill();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            mProduct = new ListProductModel();
            mInventory = new InventoryModel();
            xtraTabControl1.SelectedTabPageIndex = 0;
            LoadDataProduct();
        }
        private void LoadDataProduct()
        {
            dtProduct = new DataTable();
            dtProduct = mProduct.getAllProduct();
            gridProduct.DataSource = dtProduct;
        }
        private void LoadDataInventory()
        {
            dtInventory = new DataTable();
            dtInventory = mInventory.getAllInventory();
            gridProductDetail.DataSource = dtInventory;
        }
        private void LoadDataOrder()
        {
            //inventory
            dtInventory = new DataTable();
            dtInventory = mInventory.getAllInventory();
            gv1.DataSource = dtInventory;

            //order
            dtOrder = new DataTable();
            dtOrder.Columns.Add("name");
            dtOrder.Columns.Add("product_code");
            dtOrder.Columns.Add("qr_code");
            dtOrder.Columns.Add("weight");
            dtOrder.Columns.Add("created_date");
            gv2.DataSource = dtOrder;

            //product
            dtProduct = new DataTable();
            dtProduct.Columns.Add("name");
            dtProduct.Columns.Add("product_code");
            dtProduct.Columns.Add("weight",typeof(float));
            gv3.DataSource = dtProduct;

            //set point focus
            txtOrderQrCode.Select();
        }   

        private void navBarProduct_LinkClicked(object sender, DevExpress.XtraNavBar.NavBarLinkEventArgs e)
        {
            xtraTabControl1.SelectedTabPageIndex = 0;
            LoadDataProduct();
        }

        private void navBarProductDetail_LinkClicked(object sender, DevExpress.XtraNavBar.NavBarLinkEventArgs e)
        {
            xtraTabControl1.SelectedTabPageIndex = 1;
            LoadDataInventory();
        }
        private void navBarOrder_LinkClicked(object sender, DevExpress.XtraNavBar.NavBarLinkEventArgs e)
        {
            xtraTabControl1.SelectedTabPageIndex = 2;
            LoadDataOrder();
        }
        private void gridView3_DoubleClick(object sender, EventArgs e)
        {
            GridView view = (GridView)sender;
            Point pt = view.GridControl.PointToClient(Control.MousePosition);
            GridHitInfo info = view.CalcHitInfo(pt);
            if (info.InRow || info.InRowCell)
            {
                txtOrderQrCode.Text = view.GetRowCellValue(view.GetSelectedRows()[0], "qr_code").ToString();
            }
        }
        private void orderWithQrCode(String qr_code) 
        {
            //get value to order inventory gridcontrol & delete value on inventory grid control
            DataRow[] arrRowInventory = dtInventory.Select(String.Format("qr_code = '{0}'",qr_code));

            //add new row to order inventory grid control
            dtOrder.ImportRow(arrRowInventory[0]);
            gv2.RefreshDataSource();

            //get value to product gridcontrol
            string[] arrCode = qr_code.Split('.');
            string product_code = arrCode[0];
            bool product_code_found = false;
            for (int i = 0; i < dtProduct.Rows.Count; i++) 
            {
                if (dtProduct.Rows[i]["product_code"].Equals(product_code)) 
                {
                    float weight = float.Parse(dtProduct.Rows[i]["weight"].ToString()) + float.Parse(arrRowInventory[0]["weight"].ToString());
                    dtProduct.Rows[i]["weight"] = weight.ToString();
                    product_code_found = true;
                }
            }
            if (!product_code_found) 
            {
                dtProduct.ImportRow(arrRowInventory[0]);
            }
            //update row on product grid control
            gv3.RefreshDataSource();

            //delete row on inventory grid control
            dtInventory.Rows.Remove(arrRowInventory[0]);
            gv1.RefreshDataSource();

            //get sum weight
            lblSumWeight.Text = dtProduct.Compute("SUM(weight)", String.Empty).ToString();
        }

        private void txtQrCode_TextChanged(object sender, EventArgs e)
        {
            if (txtOrderQrCode.Text.Length == 27) 
            {
                orderWithQrCode(txtOrderQrCode.Text.ToString());
            }
        }

        private void txtOrderSearchProductName_TextChanged(object sender, EventArgs e)
        {
            customFilterInventory();
        }

        private void txtOrderSearchProductCode_TextChanged(object sender, EventArgs e)
        {
            customFilterInventory();
        }

        private void customFilterInventory() 
        {

            String key1 = "name",
                   key2 = "product_code";
            String value1 = txtOrderSearchProductName.Text.ToString(),
                   value2 = txtOrderSearchProductCode.Text.ToString();

            String filterString = "1 = 1 ";

            if (!value1.Equals(""))
            {
                filterString += String.Format(" AND [{0}] LIKE '%{1}%'", key1, value1);
            }
            if (!value2.Equals(""))
            {
                filterString += String.Format(" AND [{0}] LIKE '%{1}%'", key2, value2);
            }
            gridOrderInventory.ActiveFilterString = filterString;
        }

        private void btnOrderInventoryDelete_Click(object sender, EventArgs e)
        {
            DialogResult result = MessageBox.Show("Would you like to delete this record ?",
            "Important Question",
            MessageBoxButtons.YesNo);

            //delete when clicked to yes button on message box
            if (result == DialogResult.Yes)
            {

                DataRow[] row = new DataRow[gridOrderOrderInventory.SelectedRowsCount];
                row[0] = gridOrderOrderInventory.GetDataRow(gridOrderOrderInventory.GetSelectedRows()[0]);

                //update inventory gridcontrol
                dtInventory.ImportRow(row[0]);
                gv1.RefreshDataSource();

                //update product gridcontrol
                string product_code = row[0]["product_Code"].ToString();
                for (int i = 0; i < dtProduct.Rows.Count; i++)
                {
                    if (dtProduct.Rows[i]["product_code"].Equals(product_code))
                    {
                        float weight = float.Parse(dtProduct.Rows[i]["weight"].ToString()) - float.Parse(row[0]["weight"].ToString());
                        if (weight.ToString() == "0") //delete
                        {
                            dtProduct.Rows.RemoveAt(i);
                        }
                        else //update
                        {
                            dtProduct.Rows[i]["weight"] = weight.ToString();
                        }
                    }
                }

                gv3.RefreshDataSource();

                //delete order inventory gridcontrol
                dtOrder.Rows.Remove(row[0]);
                gv2.RefreshDataSource();
            }
        }

        private void btnOrderProductDelete_Click(object sender, EventArgs e)
        {
            DialogResult result = MessageBox.Show("Would you like to delete this record ?",
            "Important Question",
            MessageBoxButtons.YesNo);

            //delete when clicked to yes button on message box
            if (result == DialogResult.Yes)
            {
                DataRow[] rowProductSelected = new DataRow[1];
                rowProductSelected[0] = gridOrderOrderProduct.GetDataRow(gridOrderOrderProduct.GetSelectedRows()[0]);
                string product_code = rowProductSelected[0]["product_Code"].ToString();
                List<DataRow> list = new List<DataRow>();
                for (int i = 0; i < dtOrder.Rows.Count; i++)
                {
                    if (dtOrder.Rows[i]["product_code"].Equals(product_code))
                    {
                        DataRow[] rowInventorySelected = new DataRow[1];
                        rowInventorySelected[0] = gridOrderOrderInventory.GetDataRow(i);
                        list.Add(rowInventorySelected[0]);
                    }
                }

                //update inventory + order inventory gridcontrol
                foreach (DataRow dr in list)
                {
                    dtInventory.ImportRow(dr);
                    dtOrder.Rows.Remove(dr);
                }
                gv1.RefreshDataSource();
                gv2.RefreshDataSource();

                //delete product gridcontrol
                dtProduct.Rows.RemoveAt(gridOrderOrderProduct.FocusedRowHandle);
                gv3.RefreshDataSource();
            }
        }

        private void btnOrderSubmit_Click(object sender, EventArgs e)
        {
            MessageBox.Show("Order Successfully!!!");
        }

        private void btnInventoryInsertNew_Click(object sender, EventArgs e)
        {
            Hashtable hInventory = new Hashtable();
            hInventory.Add("qr_code", txtInventoryBarCodeInsert.Text.ToString());
            hInventory.Add("weight", txtInventoryWeightInsert.Text.ToString());
            hInventory.Add("status", 1);

            if (mInventory.insertNewInventory(hInventory) > 0)
            {
                MessageBox.Show("Insert Successfully!!!");
            }
            else 
            {
                MessageBox.Show("Insert Failed!!!");
            }
        }
    }
}
